name: CI
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: base_env
  TAG: v1

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@v3
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

#      - name: Cache Docker layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx
#      - name: build and push
#        run: |
#          cd dockerfiles
#          docker build -t ${{env.REGISTRY}}/qrort/base_env:v1 .
#          docker push ${{env.REGISTRY}}/qrort/base_env:v1
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          file: dockerfiles/Dockerfile
          tags: ${{env.REGISTRY}}/qrort/base_env:v1
          #cache-from: type=local,src=/tmp/.buildx-cache
          #cache-to: type=local,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

#  run-application:
#    runs-on: ubuntu-latest
#    needs: build-docker
#    steps:
#      - uses: ./.github/actions/build-action