name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/Dockerfile
          outputs: type=docker,dest=/tmp/base_env.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: base_env
          path: /tmp/base_env.tar

  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: base_env
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/base_env.tar
          ./build.sh
