name: Remove old artifacts

on:
  push:
  schedule:
    # Every hour at 0 minutes
    - cron: '0 * * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1